### Define parameters from ARTUS ###
#-name of the parameter in artus ntuple
#-binning
#-name of output plot
#-xlabel

m_vis:
- "m_vis"
- ["20,30,120"]
- "VisibleMass"
- "m_{vis} [GeV]"

pt_ll:
- "diLepLV.Pt()"
- ["20,0,100"]
- "DiLepPt"
- "p^{ll}_{T} [GeV]"
- "(diLepLV.Pt(){side}{cut})"

njets:
- "njetspt30"
- ["4,0,4"]
- "NumberOfJets"
- "Number of jets"
